version: '3.8'
services:
  postgres:
    image: postgres:18
    container_name: postgres18-ticket-shicket
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket-shicket
    ports:
      - "54322:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
