version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket_shicket_postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ticket_shicket_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: ticket_shicket_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=ls-bEkONiVE-JiQe-5222-2125-LeXarakI858c
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  nats:
    image: nats:latest
    container_name: ticket_shicket_nats
    ports:
      - "4222:4222"   # client connections
      - "8222:8222"   # monitoring
    command: ["-js", "-sd", "/data"]
    volumes:
      - nats_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  localstack_data:
  nats_data: