"""empty message

Revision ID: 0a32de8db265
Revises: c1d2e3f4g5h6
Create Date: 2026-04-15 01:20:15.860302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a32de8db265'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_user_id'), 'super_admins', ['user_id'], unique=True)
    op.create_table('b2b_requests',
    sa.Column('requesting_organizer_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved_free', 'approved_paid', 'rejected', 'expired', name='b2brequeststatus'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('allocation_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requesting_organizer_id'], ['organizer_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_requests_event_id'), 'b2b_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_b2b_requests_requesting_organizer_id'), 'b2b_requests', ['requesting_organizer_id'], unique=False)
    op.create_index(op.f('ix_b2b_requests_status'), 'b2b_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_b2b_requests_status'), table_name='b2b_requests')
    op.drop_index(op.f('ix_b2b_requests_requesting_organizer_id'), table_name='b2b_requests')
    op.drop_index(op.f('ix_b2b_requests_event_id'), table_name='b2b_requests')
    op.drop_table('b2b_requests')
    op.drop_index(op.f('ix_super_admins_user_id'), table_name='super_admins')
    op.drop_table('super_admins')
    # ### end Alembic commands ###
