"""empty message

Revision ID: 12287d5104de
Revises: 479742328475
Create Date: 2026-04-11 17:38:45.475624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12287d5104de'
down_revision = '479742328475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_created_by_id'), 'invites', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_index(op.f('ix_invites_target_user_id'), 'invites', ['target_user_id'], unique=False)
    op.create_table('event_resellers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_event_reseller_user_event')
    )
    op.create_index(op.f('ix_event_resellers_event_id'), 'event_resellers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_resellers_user_id'), 'event_resellers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_resellers_user_id'), table_name='event_resellers')
    op.drop_index(op.f('ix_event_resellers_event_id'), table_name='event_resellers')
    op.drop_table('event_resellers')
    op.drop_index(op.f('ix_invites_target_user_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_created_by_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
