"""add_coupons

Revision ID: 38799b1a5f96
Revises: 875d9b409ccc
Create Date: 2026-05-07 11:33:16.593904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38799b1a5f96'
down_revision = '875d9b409ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('FLAT', 'PERCENTAGE', name='coupontype'), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('max_discount', sa.Numeric(), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('order_coupons',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('coupon_id', sa.Uuid(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_coupons_coupon_id'), 'order_coupons', ['coupon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_coupons_coupon_id'), table_name='order_coupons')
    op.drop_table('order_coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
