"""change days_count default to -1 for zero-based day_index

Revision ID: 3bca6e2a9b45
Revises: 45787abf577
Create Date: 2026-04-18 18:01:35.371962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bca6e2a9b45'
down_revision = '45787abf577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Backfill existing events with days to -1 so next day_index starts at 0
    op.execute("""
        UPDATE events
        SET days_count = -1
        WHERE days_count = 0
        AND EXISTS (SELECT 1 FROM event_days WHERE event_days.event_id = events.id)
    """)
    # Change default going forward
    op.alter_column('events', 'days_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('-1'),
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'days_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
