"""add claim_link_id to tickets

Revision ID: 3e3562fc8e6d
Revises: e3f1d0b2f77a
Create Date: 2026-04-26 17:19:28.400723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3562fc8e6d'
down_revision = 'e3f1d0b2f77a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('claim_link_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tickets_claim_link_id'), 'tickets', ['claim_link_id'], unique=False)
    op.create_foreign_key(
        'fk_tickets_claim_link_id_claim_links',
        'tickets',
        'claim_links',
        ['claim_link_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tickets_claim_link_id_claim_links', 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_claim_link_id'), table_name='tickets')
    op.drop_column('tickets', 'claim_link_id')
    # ### end Alembic commands ###
