"""empty message

Revision ID: 479742328475
Revises: d5ede614f47b
Create Date: 2026-04-10 17:47:50.268523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '479742328475'
down_revision = 'd5ede614f47b'
branch_labels = None
depends_on = None

asset_type_enum = ENUM(
    'banner', 'gallery_image', 'gallery_video', 'promo_video',
    name='assettype',
    create_type=False
)


def upgrade() -> None:
    # Create the enum type first if it doesn't exist
    op.execute("DO $$ BEGIN CREATE TYPE assettype AS ENUM ('banner', 'gallery_image', 'gallery_video', 'promo_video'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_media_assets', 'asset_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('banner', 'gallery_image', 'gallery_video', 'promo_video', name='assettype'),
               existing_nullable=False,
               postgresql_using='asset_type::assettype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_media_assets', 'asset_type',
               existing_type=sa.Enum('banner', 'gallery_image', 'gallery_video', 'promo_video', name='assettype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
