"""empty message

Revision ID: 760216553727
Revises: 
Create Date: 2026-04-15 22:30:16.714187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '760216553727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('guests',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('converted_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_device_id'), 'guests', ['device_id'], unique=True)
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.create_table('invites',
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invite_type', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_created_by_id'), 'invites', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_index(op.f('ix_invites_target_user_id'), 'invites', ['target_user_id'], unique=False)
    op.create_table('organizer_pages',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', name='organizervisibility'), server_default=sa.text("'private'"), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='organizerstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_pages_name'), 'organizer_pages', ['name'], unique=False)
    op.create_index(op.f('ix_organizer_pages_owner_user_id'), 'organizer_pages', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizer_pages_slug'), 'organizer_pages', ['slug'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('super_admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_user_id'), 'super_admins', ['user_id'], unique=True)
    op.create_table('ticket_holders',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', name='ticketholderstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR email IS NOT NULL', name='ck_ticket_holders_has_contact'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_ticket_holders_user_id'), 'ticket_holders', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('organizer_page_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='eventstatus'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('event_access_type', sa.Enum('open', 'ticketed', name='eventaccesstype'), server_default=sa.text("'ticketed'"), nullable=False),
    sa.Column('setup_status', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('location_mode', sa.Enum('venue', 'online', 'recorded', 'hybrid', name='locationmode'), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_city', sa.String(length=255), nullable=True),
    sa.Column('venue_state', sa.String(length=255), nullable=True),
    sa.Column('venue_country', sa.String(length=255), nullable=True),
    sa.Column('venue_latitude', sa.Numeric(), nullable=True),
    sa.Column('venue_longitude', sa.Numeric(), nullable=True),
    sa.Column('venue_google_place_id', sa.String(length=255), nullable=True),
    sa.Column('online_event_url', sa.Text(), nullable=True),
    sa.Column('recorded_event_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('show_tickets', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('interested_counter', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organizer_page_id'], ['organizer_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_by_user_id'), 'events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_events_organizer_page_id'), 'events', ['organizer_page_id'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('guest_refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_refresh_tokens_guest_id'), 'guest_refresh_tokens', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_refresh_tokens_token_hash'), 'guest_refresh_tokens', ['token_hash'], unique=True)
    op.create_table('allocation_edges',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'from_holder_id', 'to_holder_id', name='uq_allocation_edges_event_from_to')
    )
    op.create_index(op.f('ix_allocation_edges_event_id'), 'allocation_edges', ['event_id'], unique=False)
    op.create_index(op.f('ix_allocation_edges_to_holder_id'), 'allocation_edges', ['to_holder_id'], unique=False)
    op.create_table('event_days',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('scan_status', sa.Enum('not_started', 'active', 'paused', 'ended', name='scanstatus'), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('scan_started_at', sa.DateTime(), nullable=True),
    sa.Column('scan_paused_at', sa.DateTime(), nullable=True),
    sa.Column('scan_ended_at', sa.DateTime(), nullable=True),
    sa.Column('next_ticket_index', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'day_index', name='uq_event_days_event_id_day_index')
    )
    op.create_index(op.f('ix_event_days_event_id'), 'event_days', ['event_id'], unique=False)
    op.create_table('event_interests',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'guest_id', name='uq_event_interests_event_guest'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_interests_event_user')
    )
    op.create_index(op.f('ix_event_interests_event_id'), 'event_interests', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_interests_guest_id'), 'event_interests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_event_interests_user_id'), 'event_interests', ['user_id'], unique=False)
    op.create_table('event_media_assets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('banner', 'gallery_image', 'gallery_video', 'promo_video', name='assettype'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_media_assets_event_id'), 'event_media_assets', ['event_id'], unique=False)
    op.create_table('event_resellers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_event_reseller_user_event')
    )
    op.create_index(op.f('ix_event_resellers_event_id'), 'event_resellers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_resellers_user_id'), 'event_resellers', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('purchase', 'transfer', name='ordertype'), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('final_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'expired', name='orderstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    op.create_table('ticket_types',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('online', 'b2b', 'public', 'vip', name='ticketcategory'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.create_table('allocations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='allocationstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ticket_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['ticket_holders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['ticket_holders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_event_id'), 'allocations', ['event_id'], unique=False)
    op.create_index(op.f('ix_allocations_from_holder_id'), 'allocations', ['from_holder_id'], unique=False)
    op.create_index(op.f('ix_allocations_status'), 'allocations', ['status'], unique=False)
    op.create_index(op.f('ix_allocations_to_holder_id'), 'allocations', ['to_holder_id'], unique=False)
    op.create_table('day_ticket_allocations',
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_day_ticket_allocations_quantity_positive'),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_day_id', 'ticket_type_id', name='uq_day_ticket_allocations_event_day_ticket_type')
    )
    op.create_index(op.f('ix_day_ticket_allocations_event_day_id'), 'day_ticket_allocations', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_day_ticket_allocations_ticket_type_id'), 'day_ticket_allocations', ['ticket_type_id'], unique=False)
    op.create_table('scan_status_history',
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_status_history_changed_by_user_id'), 'scan_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_scan_status_history_event_day_id'), 'scan_status_history', ['event_day_id'], unique=False)
    op.create_table('tickets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_index', sa.Integer(), nullable=False),
    sa.Column('seat_label', sa.String(), nullable=True),
    sa.Column('seat_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_holder_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'used', name='ticketstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('lock_reference_type', sa.String(length=32), nullable=True),
    sa.Column('lock_reference_id', sa.UUID(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['owner_holder_id'], ['ticket_holders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_day_id', 'ticket_index', name='uq_tickets_event_day_ticket_index')
    )
    op.create_index(op.f('ix_tickets_event_day_id'), 'tickets', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_owner_holder_id'), 'tickets', ['owner_holder_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_type_id'), 'tickets', ['ticket_type_id'], unique=False)
    op.create_table('allocation_tickets',
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id', 'ticket_id')
    )
    op.create_index(op.f('ix_allocation_tickets_ticket_id'), 'allocation_tickets', ['ticket_id'], unique=False)
    op.create_table('b2b_requests',
    sa.Column('requesting_organizer_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved_free', 'approved_paid', 'rejected', 'expired', name='b2brequeststatus'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('allocation_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requesting_organizer_id'], ['organizer_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_requests_event_id'), 'b2b_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_b2b_requests_requesting_organizer_id'), 'b2b_requests', ['requesting_organizer_id'], unique=False)
    op.create_index(op.f('ix_b2b_requests_status'), 'b2b_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_b2b_requests_status'), table_name='b2b_requests')
    op.drop_index(op.f('ix_b2b_requests_requesting_organizer_id'), table_name='b2b_requests')
    op.drop_index(op.f('ix_b2b_requests_event_id'), table_name='b2b_requests')
    op.drop_table('b2b_requests')
    op.drop_index(op.f('ix_allocation_tickets_ticket_id'), table_name='allocation_tickets')
    op.drop_table('allocation_tickets')
    op.drop_index(op.f('ix_tickets_ticket_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_owner_holder_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_day_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_scan_status_history_event_day_id'), table_name='scan_status_history')
    op.drop_index(op.f('ix_scan_status_history_changed_by_user_id'), table_name='scan_status_history')
    op.drop_table('scan_status_history')
    op.drop_index(op.f('ix_day_ticket_allocations_ticket_type_id'), table_name='day_ticket_allocations')
    op.drop_index(op.f('ix_day_ticket_allocations_event_day_id'), table_name='day_ticket_allocations')
    op.drop_table('day_ticket_allocations')
    op.drop_index(op.f('ix_allocations_to_holder_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_status'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_from_holder_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_event_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_orders_event_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_event_resellers_user_id'), table_name='event_resellers')
    op.drop_index(op.f('ix_event_resellers_event_id'), table_name='event_resellers')
    op.drop_table('event_resellers')
    op.drop_index(op.f('ix_event_media_assets_event_id'), table_name='event_media_assets')
    op.drop_table('event_media_assets')
    op.drop_index(op.f('ix_event_interests_user_id'), table_name='event_interests')
    op.drop_index(op.f('ix_event_interests_guest_id'), table_name='event_interests')
    op.drop_index(op.f('ix_event_interests_event_id'), table_name='event_interests')
    op.drop_table('event_interests')
    op.drop_index(op.f('ix_event_days_event_id'), table_name='event_days')
    op.drop_table('event_days')
    op.drop_index(op.f('ix_allocation_edges_to_holder_id'), table_name='allocation_edges')
    op.drop_index(op.f('ix_allocation_edges_event_id'), table_name='allocation_edges')
    op.drop_table('allocation_edges')
    op.drop_index(op.f('ix_guest_refresh_tokens_token_hash'), table_name='guest_refresh_tokens')
    op.drop_index(op.f('ix_guest_refresh_tokens_guest_id'), table_name='guest_refresh_tokens')
    op.drop_table('guest_refresh_tokens')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_page_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_ticket_holders_user_id'), table_name='ticket_holders')
    op.drop_table('ticket_holders')
    op.drop_index(op.f('ix_super_admins_user_id'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_organizer_pages_slug'), table_name='organizer_pages')
    op.drop_index(op.f('ix_organizer_pages_owner_user_id'), table_name='organizer_pages')
    op.drop_index(op.f('ix_organizer_pages_name'), table_name='organizer_pages')
    op.drop_table('organizer_pages')
    op.drop_index(op.f('ix_invites_target_user_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_created_by_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_index(op.f('ix_guests_device_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
