"""empty message

Revision ID: 7c7609b23301
Revises: 760216553727
Create Date: 2026-04-15 22:56:04.168628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7609b23301'
down_revision = '760216553727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_b2b_requests_requesting_organizer_id'), table_name='b2b_requests')
    op.drop_constraint(op.f('b2b_requests_requesting_organizer_id_fkey'), 'b2b_requests', type_='foreignkey')
    op.drop_column('b2b_requests', 'requesting_organizer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b2b_requests', sa.Column('requesting_organizer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('b2b_requests_requesting_organizer_id_fkey'), 'b2b_requests', 'organizer_pages', ['requesting_organizer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_b2b_requests_requesting_organizer_id'), 'b2b_requests', ['requesting_organizer_id'], unique=False)
    # ### end Alembic commands ###
