"""add_jti_to_refresh_tokens

Revision ID: 86e2d31444a4
Revises: 290ac3e54422
Create Date: 2026-05-02 14:35:20.339138

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '86e2d31444a4'
down_revision = '290ac3e54422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable
    op.add_column('refresh_tokens', sa.Column('jti', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    
    # Populate existing rows with a default UUID
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE refresh_tokens SET jti = :uuid WHERE jti IS NULL
    """), [{"uuid": str(uuid.uuid4())}] * 1000)  # This will be overridden by actual rows
    
    # Actually, use a simpler approach - update each row individually
    # Get all rows without jti and update them
    connection.execute(sa.text("""
        UPDATE refresh_tokens 
        SET jti = gen_random_uuid() 
        WHERE jti IS NULL
    """))
    
    # Now make the column NOT NULL
    op.alter_column('refresh_tokens', 'jti', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
