"""empty message

Revision ID: 875d9b409ccc
Revises: f156020a6408
Create Date: 2026-05-04 19:22:47.949065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875d9b409ccc'
down_revision = 'f156020a6408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sender_holder_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('receiver_holder_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('transfer_type', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('event_day_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_receiver_holder_id'), 'orders', ['receiver_holder_id'], unique=False)
    op.create_index(op.f('ix_orders_sender_holder_id'), 'orders', ['sender_holder_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'ticket_holders', ['receiver_holder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'event_days', ['event_day_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'ticket_holders', ['sender_holder_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payment_gateway_events_gateway_payment_id'), table_name='payment_gateway_events')
    op.create_index('ix_payment_gateway_events_gateway_payment_id', 'payment_gateway_events', ['gateway_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_gateway_events_gateway_payment_id', table_name='payment_gateway_events')
    op.create_index(op.f('ix_payment_gateway_events_gateway_payment_id'), 'payment_gateway_events', ['gateway_payment_id'], unique=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_sender_holder_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_receiver_holder_id'), table_name='orders')
    op.drop_column('orders', 'event_day_id')
    op.drop_column('orders', 'transfer_type')
    op.drop_column('orders', 'receiver_holder_id')
    op.drop_column('orders', 'sender_holder_id')
    # ### end Alembic commands ###
