"""add phase one event tables

Revision ID: 91180041173a
Revises: b27c8820610c
Create Date: 2026-04-05 21:48:26.410696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91180041173a'
down_revision = 'b27c8820610c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_pages',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(length=32), server_default=sa.text("'private'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_pages_name'), 'organizer_pages', ['name'], unique=False)
    op.create_index(op.f('ix_organizer_pages_owner_user_id'), 'organizer_pages', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizer_pages_slug'), 'organizer_pages', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('organizer_page_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('event_access_type', sa.String(length=32), server_default=sa.text("'ticketed'"), nullable=False),
    sa.Column('setup_status', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('location_mode', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_city', sa.String(length=255), nullable=True),
    sa.Column('venue_state', sa.String(length=255), nullable=True),
    sa.Column('venue_country', sa.String(length=255), nullable=True),
    sa.Column('venue_latitude', sa.Numeric(), nullable=True),
    sa.Column('venue_longitude', sa.Numeric(), nullable=True),
    sa.Column('venue_google_place_id', sa.String(length=255), nullable=True),
    sa.Column('online_event_url', sa.Text(), nullable=True),
    sa.Column('recorded_event_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organizer_page_id'], ['organizer_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_by_user_id'), 'events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_events_organizer_page_id'), 'events', ['organizer_page_id'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('event_days',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('scan_status', sa.String(length=32), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('scan_started_at', sa.DateTime(), nullable=True),
    sa.Column('scan_paused_at', sa.DateTime(), nullable=True),
    sa.Column('scan_ended_at', sa.DateTime(), nullable=True),
    sa.Column('next_ticket_index', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'day_index', name='uq_event_days_event_id_day_index')
    )
    op.create_index(op.f('ix_event_days_event_id'), 'event_days', ['event_id'], unique=False)
    op.create_table('ticket_types',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.create_table('day_ticket_allocations',
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.CheckConstraint('quantity > 0', name='ck_day_ticket_allocations_quantity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_day_id', 'ticket_type_id', name='uq_day_ticket_allocations_event_day_ticket_type')
    )
    op.create_index(op.f('ix_day_ticket_allocations_event_day_id'), 'day_ticket_allocations', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_day_ticket_allocations_ticket_type_id'), 'day_ticket_allocations', ['ticket_type_id'], unique=False)
    op.create_table('tickets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_type_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_index', sa.Integer(), nullable=False),
    sa.Column('seat_label', sa.String(), nullable=True),
    sa.Column('seat_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('locked_by_order_id', sa.Uuid(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_day_id', 'ticket_index', name='uq_tickets_event_day_ticket_index')
    )
    op.create_index(op.f('ix_tickets_event_day_id'), 'tickets', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_type_id'), 'tickets', ['ticket_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_day_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_day_ticket_allocations_ticket_type_id'), table_name='day_ticket_allocations')
    op.drop_index(op.f('ix_day_ticket_allocations_event_day_id'), table_name='day_ticket_allocations')
    op.drop_table('day_ticket_allocations')
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_event_days_event_id'), table_name='event_days')
    op.drop_table('event_days')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_page_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_organizer_pages_slug'), table_name='organizer_pages')
    op.drop_index(op.f('ix_organizer_pages_owner_user_id'), table_name='organizer_pages')
    op.drop_index(op.f('ix_organizer_pages_name'), table_name='organizer_pages')
    op.drop_table('organizer_pages')
    # ### end Alembic commands ###
