"""add invite_type to invites

Revision ID: aa037cba12e1
Revises: 12287d5104de
Create Date: 2026-04-11 18:43:44.696439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa037cba12e1'
down_revision = '12287d5104de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add as nullable, backfill existing rows, then alter to NOT NULL
    op.add_column('invites', sa.Column('invite_type', sa.String(length=50), nullable=True))
    # Backfill all existing invites with 'reseller' as default
    op.execute("UPDATE invites SET invite_type = 'reseller' WHERE invite_type IS NULL")
    # Now make it NOT NULL with default
    op.alter_column('invites', 'invite_type', nullable=False, server_default='reseller')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'invite_type')
    # ### end Alembic commands ###
