"""empty message

Revision ID: b09b4f4d48b4
Revises: e1a2b3c4d5e6
Create Date: 2026-04-14 22:49:27.186305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b09b4f4d48b4'
down_revision = 'e1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_holders',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', name='ticketholderstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR email IS NOT NULL', name='ck_ticket_holders_has_contact'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_ticket_holders_user_id'), 'ticket_holders', ['user_id'], unique=False)
    op.create_table('allocation_edges',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'from_holder_id', 'to_holder_id', name='uq_allocation_edges_event_from_to')
    )
    op.create_index(op.f('ix_allocation_edges_event_id'), 'allocation_edges', ['event_id'], unique=False)
    op.create_index(op.f('ix_allocation_edges_to_holder_id'), 'allocation_edges', ['to_holder_id'], unique=False)
    op.create_table('orders',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'TRANSFER', name='ordertype'), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('final_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'expired', name='orderstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    op.create_table('allocations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='allocationstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ticket_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['ticket_holders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['ticket_holders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_event_id'), 'allocations', ['event_id'], unique=False)
    op.create_index(op.f('ix_allocations_from_holder_id'), 'allocations', ['from_holder_id'], unique=False)
    op.create_index(op.f('ix_allocations_status'), 'allocations', ['status'], unique=False)
    op.create_index(op.f('ix_allocations_to_holder_id'), 'allocations', ['to_holder_id'], unique=False)
    op.create_table('allocation_tickets',
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id', 'ticket_id')
    )
    op.create_index(op.f('ix_allocation_tickets_ticket_id'), 'allocation_tickets', ['ticket_id'], unique=False)
    op.alter_column('event_interests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('event_interests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_event_interests_event_id'), 'event_interests', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_interests_guest_id'), 'event_interests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_event_interests_user_id'), 'event_interests', ['user_id'], unique=False)
    op.alter_column('invites', 'invite_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('tickets', sa.Column('owner_holder_id', sa.Uuid(), nullable=True))
    op.add_column('tickets', sa.Column('lock_reference_type', sa.String(length=32), nullable=True))
    op.add_column('tickets', sa.Column('lock_reference_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tickets_owner_holder_id'), 'tickets', ['owner_holder_id'], unique=False)
    op.drop_constraint(op.f('tickets_owner_user_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'ticket_holders', ['owner_holder_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tickets', 'owner_user_id')
    op.drop_column('tickets', 'locked_by_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('locked_by_order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_owner_user_id_fkey'), 'tickets', 'users', ['owner_user_id'], ['id'])
    op.drop_index(op.f('ix_tickets_owner_holder_id'), table_name='tickets')
    op.drop_column('tickets', 'lock_reference_id')
    op.drop_column('tickets', 'lock_reference_type')
    op.drop_column('tickets', 'owner_holder_id')
    op.alter_column('invites', 'invite_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'reseller'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_event_interests_user_id'), table_name='event_interests')
    op.drop_index(op.f('ix_event_interests_guest_id'), table_name='event_interests')
    op.drop_index(op.f('ix_event_interests_event_id'), table_name='event_interests')
    op.alter_column('event_interests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('event_interests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_allocation_tickets_ticket_id'), table_name='allocation_tickets')
    op.drop_table('allocation_tickets')
    op.drop_index(op.f('ix_allocations_to_holder_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_status'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_from_holder_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_event_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_orders_event_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_allocation_edges_to_holder_id'), table_name='allocation_edges')
    op.drop_index(op.f('ix_allocation_edges_event_id'), table_name='allocation_edges')
    op.drop_table('allocation_edges')
    op.drop_index(op.f('ix_ticket_holders_user_id'), table_name='ticket_holders')
    op.drop_table('ticket_holders')
    # ### end Alembic commands ###
