"""add guests table

Revision ID: b27c8820610c
Revises: 05160b3cd708
Create Date: 2026-04-03 01:52:47.858857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27c8820610c'
down_revision = '05160b3cd708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('converted_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_device_id'), 'guests', ['device_id'], unique=True)
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.create_table('guest_refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_refresh_tokens_guest_id'), 'guest_refresh_tokens', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_refresh_tokens_token_hash'), 'guest_refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_refresh_tokens_token_hash'), table_name='guest_refresh_tokens')
    op.drop_index(op.f('ix_guest_refresh_tokens_guest_id'), table_name='guest_refresh_tokens')
    op.drop_table('guest_refresh_tokens')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_index(op.f('ix_guests_device_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
