"""Add orders table and update allocations schema

Revision ID: c1d2e3f4g5h6
Revises: b09b4f4d48b4
Create Date: 2026-04-14 23:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = 'b09b4f4d48b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create orders table first
    op.create_table('orders',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'TRANSFER', name='ordertype'), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('final_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'expired', name='orderstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    
    # At this point, we need dummy data in orders table for existing allocations
    # Insert a default order for any existing allocations
    op.execute("""
        INSERT INTO orders (id, event_id, user_id, type, subtotal_amount, discount_amount, final_amount, status, created_at, updated_at)
        SELECT 
            gen_random_uuid(),
            a.event_id,
            (SELECT u.id FROM users u LIMIT 1),
            'TRANSFER',
            0,
            0,
            0,
            'pending',
            NOW(),
            NOW()
        FROM allocations a
        WHERE a.order_id IS NULL
        LIMIT 1
    """)
    
    # Now alter allocations table to add NOT NULL and FK
    op.alter_column('allocations', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    
    # Change metadata_ nullable to False
    op.alter_column('allocations', 'metadata_',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=False)
    
    # Add FK from allocations.order_id to orders.id
    op.create_foreign_key(None, 'allocations', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FK constraint
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    
    # Revert nullable settings
    op.alter_column('allocations', 'metadata_',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    
    op.alter_column('allocations', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Drop orders table
    op.drop_index(op.f('ix_orders_event_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
