"""Add scan_status_history table

Revision ID: cb3302c251d1
Revises: 91180041173a
Create Date: 2026-04-08 21:07:16.221880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3302c251d1'
down_revision = '91180041173a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_status_history',
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_status_history_changed_by_user_id'), 'scan_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_scan_status_history_event_day_id'), 'scan_status_history', ['event_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_status_history_event_day_id'), table_name='scan_status_history')
    op.drop_index(op.f('ix_scan_status_history_changed_by_user_id'), table_name='scan_status_history')
    op.drop_table('scan_status_history')
    # ### end Alembic commands ###
