"""add_gateway_flow_type_to_orders

Revision ID: ccfeeac9c9f2
Revises: f95e9c25e593
Create Date: 2026-05-10 15:23:24.278393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfeeac9c9f2'
down_revision = 'f95e9c25e593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gateway_flow_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_gateway_flow_type'), 'orders', ['gateway_flow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_gateway_flow_type'), table_name='orders')
    op.drop_column('orders', 'gateway_flow_type')
    # ### end Alembic commands ###
