"""add payment gateway fields to OrderModel and unique constraint on AllocationModel.order_id

Revision ID: cd2a50123a0f
Revises: 86e2d31444a4
Create Date: 2026-05-03 15:36:49.990501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd2a50123a0f'
down_revision = '86e2d31444a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gateway_type_enum = sa.Enum('RAZORPAY_ORDER', 'RAZORPAY_PAYMENT_LINK', 'STRIPE_CHECKOUT', name='gatewaytype', create_type=True)
    gateway_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_unique_constraint('uq_allocations_order_id', 'allocations', ['order_id'])
    op.add_column('orders', sa.Column('lock_expires_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('gateway_type', gateway_type_enum, nullable=True))
    op.add_column('orders', sa.Column('gateway_order_id', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('short_url', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('gateway_payment_id', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('captured_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_gateway_order_id'), 'orders', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_orders_gateway_payment_id'), 'orders', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_orders_lock_expires_at'), 'orders', ['lock_expires_at'], unique=False)
    op.create_index('ix_orders_pending_lock_expiry', 'orders', ['status', 'lock_expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_pending_lock_expiry', table_name='orders', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_orders_lock_expires_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_gateway_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_gateway_order_id'), table_name='orders')
    op.drop_column('orders', 'expired_at')
    op.drop_column('orders', 'captured_at')
    op.drop_column('orders', 'gateway_payment_id')
    op.drop_column('orders', 'short_url')
    op.drop_column('orders', 'gateway_response')
    op.drop_column('orders', 'gateway_order_id')
    op.drop_column('orders', 'gateway_type')
    op.drop_column('orders', 'lock_expires_at')
    op.drop_constraint('uq_allocations_order_id', 'allocations', type_='unique')
    # ### end Alembic commands ###
