"""empty message

Revision ID: d01b57798e73
Revises: 3bca6e2a9b45
Create Date: 2026-04-25 18:52:32.110355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01b57798e73'
down_revision = '3bca6e2a9b45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_scan_tokens',
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_day_id', 'jti', name='uq_revoked_scan_tokens_event_day_jti')
    )
    op.create_index(op.f('ix_revoked_scan_tokens_event_day_id'), 'revoked_scan_tokens', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_revoked_scan_tokens_jti'), 'revoked_scan_tokens', ['jti'], unique=False)
    op.create_table('claim_links',
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_day_id', sa.Uuid(), nullable=False),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='claimlinkstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_holder_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['ticket_holders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_links_allocation_id'), 'claim_links', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_claim_links_event_day_id'), 'claim_links', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_claim_links_event_id'), 'claim_links', ['event_id'], unique=False)
    op.create_index(op.f('ix_claim_links_status'), 'claim_links', ['status'], unique=False)
    op.create_index(op.f('ix_claim_links_to_holder_id'), 'claim_links', ['to_holder_id'], unique=False)
    op.create_index(op.f('ix_claim_links_token_hash'), 'claim_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_links_token_hash'), table_name='claim_links')
    op.drop_index(op.f('ix_claim_links_to_holder_id'), table_name='claim_links')
    op.drop_index(op.f('ix_claim_links_status'), table_name='claim_links')
    op.drop_index(op.f('ix_claim_links_event_id'), table_name='claim_links')
    op.drop_index(op.f('ix_claim_links_event_day_id'), table_name='claim_links')
    op.drop_index(op.f('ix_claim_links_allocation_id'), table_name='claim_links')
    op.drop_table('claim_links')
    op.drop_index(op.f('ix_revoked_scan_tokens_jti'), table_name='revoked_scan_tokens')
    op.drop_index(op.f('ix_revoked_scan_tokens_event_day_id'), table_name='revoked_scan_tokens')
    op.drop_table('revoked_scan_tokens')
    # ### end Alembic commands ###
