"""empty message

Revision ID: d5ede614f47b
Revises: 9bf5b22783b2
Create Date: 2026-04-10 16:22:50.082681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ede614f47b'
down_revision = '9bf5b22783b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_media_assets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_media_assets_event_id'), 'event_media_assets', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_media_assets_event_id'), table_name='event_media_assets')
    op.drop_table('event_media_assets')
    # ### end Alembic commands ###
