"""add_jwt_jti_to_claim_links

Revision ID: e3f1d0b2f77a
Revises: d01b57798e73
Create Date: 2026-04-26 13:05:31.595231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f1d0b2f77a'
down_revision = 'd01b57798e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_links', sa.Column('jwt_jti', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_links', 'jwt_jti')
    # ### end Alembic commands ###
