"""Add is_published field to events table

Revision ID: ea0828634684
Revises: cb3302c251d1
Create Date: 2026-04-08 23:29:07.542154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0828634684'
down_revision = 'cb3302c251d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_published')
    # ### end Alembic commands ###
