"""empty message

Revision ID: f156020a6408
Revises: cd2a50123a0f
Create Date: 2026-05-03 20:20:33.988692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f156020a6408'
down_revision = 'cd2a50123a0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateway_events',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('gateway_event_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_payment_id', name='uq_payment_gateway_events_payment_id'),
    sa.UniqueConstraint('order_id', 'event_type', 'gateway_event_id', name='uq_payment_gateway_events_dedup')
    )
    op.create_index(op.f('ix_payment_gateway_events_gateway_event_id'), 'payment_gateway_events', ['gateway_event_id'], unique=False)
    op.create_index(op.f('ix_payment_gateway_events_gateway_payment_id'), 'payment_gateway_events', ['gateway_payment_id'], unique=True)
    op.create_index(op.f('ix_payment_gateway_events_order_id'), 'payment_gateway_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_gateway_events_order_id'), table_name='payment_gateway_events')
    op.drop_index(op.f('ix_payment_gateway_events_gateway_payment_id'), table_name='payment_gateway_events')
    op.drop_index(op.f('ix_payment_gateway_events_gateway_event_id'), table_name='payment_gateway_events')
    op.drop_table('payment_gateway_events')
    # ### end Alembic commands ###
