"""add token column to claim_links

Revision ID: f95e9c25e593
Revises: 38799b1a5f96
Create Date: 2026-05-07 13:35:50.607891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95e9c25e593'
down_revision = '38799b1a5f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_links', sa.Column('token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_links', 'token')
    # ### end Alembic commands ###
