// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByemail = `-- name: getUserByemail :one
SELECT id, name, email, password_hash
FROM users
WHERE email = $1 AND is_active = true
`

type getUserByemailRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) getUserByemail(ctx context.Context, email string) (getUserByemailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByemail, email)
	var i getUserByemailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
