// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (user_agent, ip_address, created_at, last_active)
VALUES ($1, $2, NOW(), NOW())
RETURNING guest_id, user_agent, ip_address, created_at, last_active, slug
`

type CreateGuestParams struct {
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, createGuest, arg.UserAgent, arg.IpAddress)
	var i Guest
	err := row.Scan(
		&i.GuestID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActive,
		&i.Slug,
	)
	return i, err
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT guest_id, user_agent, ip_address, created_at, last_active, slug
FROM guests
WHERE guest_id = $1
`

func (q *Queries) GetGuestByID(ctx context.Context, guestID uuid.UUID) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByID, guestID)
	var i Guest
	err := row.Scan(
		&i.GuestID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActive,
		&i.Slug,
	)
	return i, err
}

const updateGuestLastActive = `-- name: UpdateGuestLastActive :one
UPDATE guests
SET last_active = NOW()
WHERE guest_id = $1
RETURNING guest_id, user_agent, ip_address, created_at, last_active, slug
`

func (q *Queries) UpdateGuestLastActive(ctx context.Context, guestID uuid.UUID) (Guest, error) {
	row := q.db.QueryRowContext(ctx, updateGuestLastActive, guestID)
	var i Guest
	err := row.Scan(
		&i.GuestID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActive,
		&i.Slug,
	)
	return i, err
}
