from pathlib import Path
from typing import Dict, List, Optional

import uvicorn
from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected
from rich.console import Console
from rich.panel import Panel
from rich.theme import Theme
from typer import Typer

from config import settings
from server import create_app

console = Console(
    theme=Theme(
        {
            "info": "cyan",
            "warning": "yellow",
            "error": "red",
            "success": "green",
            "highlight": "magenta bold",
            "header": "cyan bold",
            "file": "green",
            "directory": "blue",
            "progress": "green",
            "command": "yellow bold",
        }
    )
)


class ColoredOutput:
    @staticmethod
    def success(message: str) -> str:
        return f"[success]✅ {message}[/]"

    @staticmethod
    def info(message: str) -> str:
        return f"[info]ℹ️  {message}[/]"

    @staticmethod
    def warning(message: str) -> str:
        return f"[warning]⚠️  {message}[/]"

    @staticmethod
    def error(message: str) -> str:
        return f"[error]❌ {message}[/]"

    @staticmethod
    def highlight(message: str) -> str:
        return f"[highlight]{message}[/]"

    @staticmethod
    def file_created(file_path: str) -> str:
        return f"[file]📄 Created file: [bold]{file_path}[/][/]"

    @staticmethod
    def directory_created(dir_path: str) -> str:
        return f"[directory]📁 Created directory: [bold]{dir_path}[/][/]"

    @staticmethod
    def header(message: str) -> str:
        border = "═" * (len(message) + 4)
        return f"\n[header]{border}\n  {message.upper()}\n{border}[/]\n"


class AppGenerator:
    def __init__(self, app_name: str):
        self.app_name = app_name
        self.base_path = Path("src/apps") / app_name

    def create_directory_structure(self) -> None:
        console.print(ColoredOutput.header("Creating Directory Structure"))
        self.base_path.mkdir(parents=True, exist_ok=True)
        console.print(ColoredOutput.directory_created(str(self.base_path)))

    def get_file_contents(self) -> Dict[Path, str]:
        n = self.app_name
        title = n.title()
        return {
            self.base_path / "__init__.py": f"from .urls import router as {n}_router\n\n__all__ = [\"{n}_router\"]\n",
            self.base_path / "models.py": f"""import uuid
from typing import Self

from sqlalchemy.orm import Mapped, mapped_column

from db.base import Base, TimeStampMixin, UUIDPrimaryKeyMixin


class {title}Model(Base, UUIDPrimaryKeyMixin, TimeStampMixin):
    __tablename__ = "{n}"
    # define your fields here
    pass
""",
            self.base_path / "repository.py": f"""from typing import Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .models import {title}Model


class {title}Repository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    @property
    def session(self) -> AsyncSession:
        return self._session

    # write your repository methods here
""",
            self.base_path / "service.py": f"""from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .repository import {title}Repository


class {title}Service:
    def __init__(self, repository: "{title}Repository") -> None:
        self.repository = repository

    # write your service methods here
""",
            self.base_path / "request.py": f"""from utils.schema import CamelCaseModel


class CreateRequest(CamelCaseModel):
    pass


class UpdateRequest(CamelCaseModel):
    pass
""",
            self.base_path / "response.py": f"""from utils.schema import BaseResponse, CamelCaseModel


class SampleResponse(BaseResponse):
    pass
""",
            self.base_path / "exceptions.py": f"""import constants
from exceptions import CustomException, NotFoundError, UnauthorizedError, UnprocessableEntityError, BadRequestError

# create your custom exception classes here
""",
            self.base_path / "urls.py": f"""from typing import Annotated
from fastapi import APIRouter, Body, Depends, status

from .request import CreateRequest, UpdateRequest
from .response import SampleResponse
from .service import {title}Service
from .repository import {title}Repository
from db.session import db_session

router = APIRouter(prefix="/api/{n}", tags=["{title}"])


def get_{n}_service(session: db_session) -> {title}Service:
    return {title}Service({title}Repository(session))


# Create your routes here
# Example:
# @router.post("")
# async def create_{n}(
#     body: Annotated[CreateRequest, Body()],
#     service: Annotated[{title}Service, Depends(get_{n}_service)],
# ):
#     pass
""",
        }

    def show_summary(self) -> None:
        n = self.app_name
        console.print(ColoredOutput.header("FastAPI App Generation Complete"))
        console.print(ColoredOutput.success(f"Successfully created FastAPI app '{n}'!"))
        console.print(ColoredOutput.info(f"App structure created at: {self.base_path.absolute()}"))
        console.print("\n[header]📂 Directory Structure:[/]")
        for line in [
            f"src/apps/{n}/",
            f"├── __init__.py",
            f"├── models.py",
            f"├── repository.py",
            f"├── service.py",
            f"├── request.py",
            f"├── response.py",
            f"├── exceptions.py",
            f"└── urls.py",
        ]:
            console.print(f"[directory]{line}[/]")
        console.print("\n[command]🚀 Next Steps:[/]")
        console.print(ColoredOutput.info(f"1. Import your router in src/apps/__init__.py"))
        console.print(ColoredOutput.info(f"2. Import your router in src/server.py"))
        console.print(ColoredOutput.info("Your FastAPI application is ready to use!"))


cli = Typer(pretty_exceptions_show_locals=False)
alembic_cfg = Config()
alembic_cfg.set_main_option("script_location", "src/migrations")
alembic_cfg.set_main_option("sqlalchemy.url", settings.DATABASE_URL)
alembic_cfg.set_main_option("compare_type", "true")


@cli.command(help="Create a new FastAPI application structure")
def startapp(app_name: str, verbose: bool = False) -> None:
    try:
        app_path = Path("src/apps") / app_name
        if app_path.exists():
            console.print(ColoredOutput.error(f"Directory '{app_name}' already exists!"))
            return

        console.print(ColoredOutput.header("FastAPI App Generator"))
        console.print(ColoredOutput.info(f"Creating new FastAPI application: {ColoredOutput.highlight(app_name)}"))

        generator = AppGenerator(app_name)
        generator.create_directory_structure()
        console.print(ColoredOutput.header("Creating Application Files"))

        files_content = generator.get_file_contents()
        total_files = len(files_content)

        for i, (file_path, content) in enumerate(files_content.items(), 1):
            file_path.write_text(content)
            if verbose:
                console.print(ColoredOutput.file_created(str(file_path)))
            else:
                progress = f"[{i}/{total_files}]"
                console.print(f"[progress]{progress}[/] [file]{file_path.name}[/]")

        generator.show_summary()

    except Exception as e:
        console.print(ColoredOutput.error(f"An error occurred: {str(e)}"))


@cli.command(help="Detect database changes and create migrations.")
def makemigrations(message: Optional[str] = None) -> None:
    console.print(Panel.fit("[warning]Detecting new migrations![/warning]"))
    try:
        command.check(alembic_cfg)
        console.print(Panel.fit("[success]No changes detected![/success]"))
    except AutogenerateDiffsDetected:
        console.print(Panel.fit("[warning]Changes detected! Generating migrations.[/warning]"))
        command.revision(alembic_cfg, message=message, autogenerate=True)


@cli.command(help="Show migration status.")
def showmigrations() -> None:
    import asyncio
    from alembic.script import ScriptDirectory
    from sqlalchemy import text
    from db.session import engine

    console.print(Panel.fit("[info]Migration Status[/info]"))

    script = ScriptDirectory.from_config(alembic_cfg)

    async def _get_current() -> str | None:
        async with engine.connect() as conn:
            result = await conn.execute(text("SELECT version_num FROM alembic_version"))
            return result.scalar()

    try:
        current = asyncio.run(_get_current())
    except Exception:
        current = None
    applied = {current} if current else set()

    all_migrations = list(script.walk_revisions())
    all_migrations.reverse()

    for rev in all_migrations:
        symbol = "[green]✓[/green]" if rev.revision in applied else "[red]✗[/red]"
        prefix = f"{symbol} [{rev.revision}]"
        is_current = " (current)" if rev.revision == current else ""
        console.print(f"  {prefix}{is_current}")


@cli.command(help="Migrate the database")
def migrate() -> None:
    console.print(Panel.fit("[warning]Migrating database![/warning]"))
    command.upgrade(alembic_cfg, "head")


@cli.command(help="Rollback the database by one migration")
def rollback() -> None:
    console.print(Panel.fit("[warning]Rolling back the database![/warning]"))
    command.downgrade(alembic_cfg, "-1")


@cli.command(help="Run the server")
def run(
    host: Optional[str] = None,
    port: Optional[int] = None,
    debug: Optional[bool] = False,
) -> None:
    if not host:
        host = settings.APP_HOST
    if not port:
        port = settings.APP_PORT
    if debug or settings.APP_DEBUG:
        console.print(Panel.fit("[warning]Running in debug mode![/warning]"))
        uvicorn.run(
            "server:create_app",
            host=host,
            port=port,
            reload=True,
            reload_dirs=["src"],
            log_level="debug",
            use_colors=True,
            root_path="/" if settings.APP_CONTAINER else "",
        )
    else:
        console.print(Panel.fit("[warning]Running in production mode![/warning]"))
        uvicorn.run(
            create_app(debug=False),
            host=host,
            port=port,
        )


@cli.command(help="Create multiple FastAPI application structures at once")
def startapps(app_names: List[str], verbose: bool = False) -> None:
    for app_name in app_names:
        console.print(f"[command]Creating app: [highlight]{app_name}[/]")
        startapp(app_name, verbose)
